# basic options
title: Alberto's web
author: https://github.com/AlbertoFemenias
email: 
description: This is a simple website built with Jekyll and Github Pages where I upload some small projects I have done in my spare time. Enjoy!
linkedin: 
github_username:  

# Build settings
markdown: kramdown
theme: minima
