# basic options
title: Alberto's web
author: 2017 - 2020
email: 
description: This is a simple website build with Jekyll and Github pages where I upload some small projects I have been doing over the time
linkedin_username: alberto-femenías-hermida-56787ba2
github_username:  AlbertoFemenias

# Build settings
markdown: kramdown
theme: minima
