# basic options
title: Alberto's web
author: 
email: 
description: This is a simple website built with Jekyll and Github Pages where I upload some small projects I have done in my spare time. Enjoy!
linkedin_username: alberto-femenías-hermida-56787ba2
github_username:  AlbertoFemenias

# Build settings
markdown: kramdown
theme: minima
